modLoader="javafml"
loaderVersion="[35,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Epidra/Uncharted/issues"
[[mods]]
modId="uncharted"
version="v07"
displayName="Uncharted" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/uncharted"
logoFile="logo.png"
credits="Thanks for this example mod goes to Java" #optional
authors="Love, Cheese and small house plants" #optional
description='''
Ever came out of a cave and didn't know where you are?
Or wondered if you are standing in a desert or just a really long beach?
Say no more.
'''
[[dependencies.uncharted]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"